resources:
  - name: docker-upx.git
    type: git
    source:
      uri: https://github.com/colstrom/docker-upx.git
  - name: upx
    type: docker-image
    source:
      repository: {{docker-repository}}
      email: {{docker-email}}
      username: {{docker-username}}
      password: {{docker-password}}
  - name: build-base
    type: docker-image
    source:
      repository: packages/build-base
  - name: upx#build
    type: docker-image
    source:
      repository: contains/upx
      tag: build
      email: {{docker-email}}
      username: {{docker-username}}
      password: {{docker-password}}
jobs:
  - name: create-build-image
    plan:
      - get: docker-upx.git
        trigger: true
      - get: build-base
        trigger: false
      - put: upx#build
        params:
          build: docker-upx.git/images/upx/build
  - name: build
    plan:
      - get: docker-upx.git
        trigger: true
      - get: upx#build
        trigger: true
      - task: fetch-ucl-source
        file: docker-upx.git/tasks/fetch-ucl-source.yaml
      - task: build-ucl
        file: docker-upx.git/tasks/build-ucl.yaml
      - aggregate:
        - task: extract-ucl-libs
          file: docker-upx.git/tasks/extract-ucl-libs.yaml
        - task: fetch-lzma-sdk
          file: docker-upx.git/tasks/fetch-lzma-sdk.yaml
        - task: fetch-upx-source
          file: docker-upx.git/tasks/fetch-upx-source.yaml
      - task: build-upx
        file: docker-upx.git/tasks/build-upx.yaml
      - task: strip-upx
        file: docker-upx.git/tasks/strip-upx.yaml
      - task: pack-upx
        file: docker-upx.git/tasks/pack-upx.yaml
      - task: prepare-docker
        file: docker-upx.git/tasks/prepare-docker.yaml
      - put: upx
        params:
          build: upx/docker
