---
platform: linux
image: docker:///busybox#musl
inputs:
  - name: docker-upx.git
  - name: upx/packed
    path: upx/bin
outputs:
  - name: upx/docker
run:
  path: docker-upx.git/scripts/prepare-docker
