#!/bin/sh

set -e -x

export VERSION=${VERSION:-'1.03'}
export OUT=${OUT:-"${PWD}/ucl/source"}

wget -O - http://www.oberhumer.com/opensource/ucl/download/ucl-${VERSION}.tar.gz | tar xz

mkdir -p $(dirname "${OUT}")
mv ucl-${VERSION} "${OUT}"
