---
platform: linux
image: docker:///contains/upx:build
inputs:
  - name: docker-upx.git
  - name: ucl/source
  - name: ucl/libs
  - name: lzma/sdk
  - name: upx/source
outputs:
  - name: upx/raw
run:
  path: docker-upx.git/ci/scripts/build-upx
